demo_pyconfr/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from conf import views

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^index/', views.index, name='index'),
    url(r'^add_speaker/', views.add_speaker, name='add_speaker'),
    url(
        r'^add_speaker/cbv/',
        views.AddSpeaker.as_view(),
        name='add_speaker_cbv'
    ),
]

conf/models.py
from django.db import models


class Speaker(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Talk(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    speaker = models.ForeignKey(Speaker)

conf/forms.py
from django import forms

from .models import Speaker


class SpeakerForm(forms.ModelForm):
    class Meta:
        model = Speaker
        fields = ('name',)

conf/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView

from .models import Speaker
from .forms import SpeakerForm


def index(request):
    speakers = Speaker.objects.all()
    return render(request, 'conf/index.html', {'speakers': speakers})


def add_speaker(request):
    if request.method == 'POST':
        form = SpeakerForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
    else:
        form = SpeakerForm()
    return render(request, 'conf/add_speaker.html', {'form': form})


class AddSpeaker(CreateView):
    template_name = 'conf/add_speaker.html'
    form_class = SpeakerForm

conf/templates/conf/add_speaker.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Speakers</title>
  </head>

  <body>

      <h1>Add Speakers</h1>

      <a href="{% url 'index' %}"><button>Cancel</button></a>

      <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Add</button>
      </form>

  </body>
</html>

conf/templates/conf/index.html
<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <title>Speakers</title>
  </head>

  <body>

      <h1>Speakers</h1>

      <a href="{% url 'add_speaker' %}"><button>New</button></a>
      <a href="{% url 'add_speaker_cbv' %}"><button>New cbv</button></a>

      {% for speaker in speakers %}

        <h2>{{ speaker.name }}</h2>

        <p><b>Talks :</b><br />

        {% for talk in speaker.talk_set.all %}
          - {{ talk.title }} : {{ talk.content }}<br />
        {% endfor %}

        <p>

      {% endfor %}

  </body>
</html>